### ISSUE TITLE
KeyError: 'k4'

### ISSUE THREAD

**Issue by 3dhermit** [joreeves/rc2nerf#5]
When I try to run the script I get this error, not sure what the issue is and any assistance would be awesome.

Command ran 
python "C:\Users\PC\Instant-NGP\scripts\rc2nerf.py" --csv_in "dog.csv" --imgfolder .\images

What returned is :
(ngp) C:\Users\PC\Instant-NGP\data\nerf\example>python "C:\Users\PC\Instant-NGP\scripts\rc2nerf.py" --csv_in "dog.csv" --imgfolder .\images
Processing reality capture csv:   2%|▊                                                  | 1/65 [00:01<01:42,  1.60s/it]Traceback (most recent call last):
  File "C:\Users\PC\.conda\envs\ngp\lib\site-packages\pandas\core\indexes\base.py", line 3653, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas\_libs\index.pyx", line 147, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\index.pyx", line 176, in pandas._libs.index.IndexEngine.get_loc
  File "pandas\_libs\hashtable_class_helper.pxi", line 7080, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas\_libs\hashtable_class_helper.pxi", line 7088, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'k4'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\PC\Instant-NGP\scripts\rc2nerf.py", line 197, in <module>
    k4=row['k4'],
  File "C:\Users\PC\.conda\envs\ngp\lib\site-packages\pandas\core\series.py", line 1007, in __getitem__
    return self._get_value(key)
  File "C:\Users\PC\.conda\envs\ngp\lib\site-packages\pandas\core\series.py", line 1116, in _get_value
    loc = self.index.get_loc(label)
  File "C:\Users\PC\.conda\envs\ngp\lib\site-packages\pandas\core\indexes\base.py", line 3655, in get_loc
    raise KeyError(key) from err
KeyError: 'k4'
Processing reality capture csv:   2%|▊                                                  | 1/65 [00:03<03:18,  3.10s/it]

**Comment by 3dhermit** [comment]
Figured the issue out, using old version of RC, the file format has changed in the newer version of RC, thank you so much for making this tool!
